const SPORTS = ["FOOTBALL","BASKETBALL","TENNIS","SWIMMING","VOLLEYBALL","HANDBALL"];
const SPORT_COLORS = { FOOTBALL:"#10b981", BASKETBALL:"#f59e0b", TENNIS:"#38bdf8", SWIMMING:"#5eead4", VOLLEYBALL:"#a78bfa", HANDBALL:"#f87171" };
const SPORT_ICONS  = { FOOTBALL:"⚽", BASKETBALL:"🏀", TENNIS:"🎾", SWIMMING:"🏊", VOLLEYBALL:"🏐", HANDBALL:"🤾" };
const ROLES = ["ADMIN","PLAYER","HEAD_COACH","ASSISTANT_COACH","FITNESS_COACH","SPECIFIC_COACH","DOCTOR","PHYSIOTHERAPIST","PERFORMANCE_ANALYST","TEAM_MANAGER","SPORT_MANAGER","SCOUT","FAN","SPONSOR"];
const PLAYER_STATUS = ["AVAILABLE","INJURED","SUSPENDED","ON_LOAN","TRANSFERRED","RETIRED"];
const CONTRACT_STATUS = ["ACTIVE","EXPIRED","TERMINATED","ON_HOLD"];
const TRANSFER_STATUS = ["PENDING","NEGOTIATING","COMPLETED","CANCELLED"];
const INJURY_TYPES = ["MUSCLE_STRAIN","LIGAMENT_SPRAIN","FRACTURE","CONTUSION","TENDONITIS","DISLOCATION","CONCUSSION"];
const INJURY_SEVERITY = ["MINOR","MODERATE","SEVERE","CRITICAL"];
const INJURY_STATUS_LIST = ["REPORTED","DIAGNOSED","TREATING","RECOVERING","RECOVERED","CHRONIC"];
const SESSION_TYPES = ["TACTICAL","TECHNICAL","FITNESS","RECOVERY","SET_PIECES"];
const SESSION_STATUS = ["SCHEDULED","IN_PROGRESS","COMPLETED","CANCELLED"];
const MATCH_TYPES = ["FRIENDLY","LEAGUE","CUP","TOURNAMENT","PRE_SEASON"];
const MATCH_STATUS = ["SCHEDULED","LIVE","FINISHED","CANCELLED","POSTPONED"];
const FITNESS_TEST_TYPES = ["VO2_MAX","SPEED_TEST","AGILITY_TEST","STRENGTH_TEST","FLEXIBILITY_TEST","ENDURANCE_TEST","BODY_COMPOSITION"];
const TREATMENT_STATUS = ["PLANNED","IN_PROGRESS","COMPLETED","CANCELLED"];
const CALLUP_STATUS = ["PENDING","APPROVED","REJECTED","COMPLETED"];
const ALERT_TYPES = ["INJURY_REPORTED","MEDICAL_CHECKUP_DUE","FITNESS_TEST_DUE","KPI_DROP","MATCH_UPCOMING","PLAYER_SUSPENSION","TRANSFER_COMPLETED","CONTRACT_EXPIRING","SCOUT_REPORT_SUBMITTED","SPONSOR_OFFER_RECEIVED","SYSTEM"];
const ALERT_PRIORITY = ["LOW","MEDIUM","HIGH","CRITICAL"];
const STAFF_ROLES = ["HEAD_COACH","ASSISTANT_COACH","FITNESS_COACH","DOCTOR","PHYSIOTHERAPIST","PERFORMANCE_ANALYST"];
const DRILL_CATEGORIES = ["WARMUP","COOLDOWN","FITNESS","TACTICAL","TECHNICAL","RECOVERY","MENTAL","VIDEO_ANALYSIS","SHOOTING_DRILL","PASSING_DRILL","DEFENDING_DRILL","SET_PLAYS","STROKE_TECHNIQUE","SERVE_PRACTICE","SPIKE_DRILL","BLOCKING_DRILL","DRIBBLING_DRILL","REBOUNDING_DRILL","AGILITY_DRILL"];
const EVENT_TYPES_BY_SPORT = {
  ALL: ["SUBSTITUTION","YELLOW_CARD","RED_CARD","INJURY","END_OF_PERIOD"],
  FOOTBALL: ["GOAL","ASSIST","OWN_GOAL","PENALTY_SCORED","PENALTY_MISSED","CORNER_KICK","FREE_KICK","VAR_REVIEW","OFFSIDE"],
  BASKETBALL: ["BASKET_2PT","BASKET_3PT","FREE_THROW_MADE","FREE_THROW_MISSED","TIMEOUT","PERSONAL_FOUL","TECHNICAL_FOUL"],
  TENNIS: ["ACE","DOUBLE_FAULT","BREAK_OF_SERVE","GAME_WON","SET_WON","MATCH_WON"],
  SWIMMING: ["RACE_START","RACE_FINISH","DISQUALIFICATION_SWIM"],
  VOLLEYBALL: ["POINT_WON","SET_WON_VB","ACE_VB","BLOCK_POINT"],
  HANDBALL: ["GOAL_HB","SEVEN_METER_THROW","GOALKEEPER_SAVE","TWO_MINUTE_SUSPENSION"],
};